repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer    # Ensure files end with a newline
      - id: check-yaml           # Validate YAML files
      - id: check-added-large-files  # Prevent large files from being committed
      - id: check-ast            # Check Python files for syntax errors
      - id: debug-statements     # Check for debug statements (e.g., pdb, ipdb)
      - id: check-merge-conflict # Check for merge conflict markers

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest stable version
    hooks:
      - id: black  # Auto-format Python code

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use the latest stable version
    hooks:
      - id: isort  # Sort Python imports

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest stable version
    hooks:
      - id: flake8  # Lint Python code

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1  # Use the latest stable version
    hooks:
      - id: mypy  # Static type checking for Python
        additional_dependencies: [types-python-dateutil, types-requests]
