services:
  stock_analysis:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: stock_analysis_tool
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
    ports:
        - "8024:8024"
    # command: python -m src --pipeline=data_collection
    command: /bin/bash -c "python -m src --pipeline=data_collection & tail -f /dev/null"
    tty: true
    stdin_open: true
