# Use an official Python runtime as a parent image
FROM python:3.11-slim



RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    curl \
    vim \
    && rm -rf /var/lib/apt/lists/*


# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements_dev.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements_dev.txt
RUN pip install rich
# Copy the rest of the application code
COPY . .

# Expose any necessary ports (if applicable)
# EXPOSE 5000

# Run the application

CMD ["python", "-m", "src", "--pipeline=data_collection"]
